base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('login/', views.loginViewPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('', views.home, name='home'),
    path('room/<str:pk>', views.room, name='room'),
    path('profile/<str:pk>', views.userProfile, name='user-profile'),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>', views.deleteMessage, name="delete-message"),
    
    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
    ]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import CASCADE


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True ,null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD_ = 'email'
    REQUIRED_FIELDS = []

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name
    
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    room = models.ForeignKey(Room, on_delete=CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50] # hasta la letra 50 """ """

base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id',
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)

    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)

    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Room, Topic, Message, User
from.forms import RoomForm, UserForm, MyUserCreationForm



def loginViewPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        email_or_username = request.POST.get('email', '').strip().lower()  # Maneja nulos y espacios
        password = request.POST.get('password', '')

        user = None
        try:
            # Verifica si se ingresó un email o un username
            if User.objects.filter(email=email_or_username).exists():
                user_obj = User.objects.get(email=email_or_username)
                user = authenticate(request, username=user_obj.username, password=password)
            else:
                user = authenticate(request, username=email_or_username, password=password)
        except User.DoesNotExist:
            messages.error(request, "User doesn't exist.")
        
        if user is not None:
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, "Email/Username or password is incorrect.")

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'An error ocurred during registration.')

    context = {'form':form}
    return render(request, 'base/login_register.html', context)



# Logout view
def logoutUser(request):
    logout(request)
    return redirect('base:home')



# Main view
def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else '' # Obtiene q del browser 
    
    # Lista de las rooms que coincidan con q
    rooms = Room.objects.filter(
        # Filtra los topicos, nombres, descriptions que incluyan q
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
        )

    # Lista de topics y contador de salas
    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {
        'rooms':rooms, 
        'topics':topics, 
        'room_count':room_count, 
        'room_messages':room_messages,
    }
    return render(request, 'base/home.html', context)



# Devuelve una room en particular con id
def room(request, pk):

    # Busca la room con id y renderiza room page
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('base:room', pk=room.id)

    context = {'room': room, 'room_messages':room_messages, 'participants':participants}
    return render(request, 'base/room.html', context)



# Profile view
def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_message = user.message_set.all()
    topics = Topic.objects.all()

    context = {
        'user':user,
        'rooms':rooms,
        'topics':topics,
        'room_messages':room_message,
        }
    return render(request, 'base/profile.html', context)



# Redirige al user al login si no está logueado e intenta crear room.
@login_required(login_url='base:login')
def createRoom(request):
    form = RoomForm() # Form predeterminado de django
    topics = Topic.objects.all()

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host = request.user,
            topic = topic,
            name = request.POST.get('name'),
            description = request.POST.get('description'),
        )
        return redirect('base:home')

    # Else renderiza el form vacío
    context = {'form':form, 'topics':topics}
    return render(request, 'base/room_form.html', context)



# View para actualizar una sala
@login_required(login_url='base:login')
def updateRoom(request, pk):
    # Busca una sala por su id
    room = Room.objects.get(id=pk)

    # Precompleta los datos de la sala con el room ya creado
    form = RoomForm(instance=room)
    topics = Topic.objects.all()

    # Maneja si algun user quiere editar un post de otro usuario
    if request.user != room.host:
        return HttpResponse('You are not alowed here!!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('base:home')

    # Manda el context actualizado, ya sea con o sin cambios.
    context = {'form': form, 'topics':topics, 'room':room}
    return render(request, 'base/room_form.html', context)



# View para borrar sala
@login_required(login_url='base:login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk) # Busca sala por id

    # Maneja si algun user quiere eliminar un post de otro usuario
    if request.user != room.host:
        return HttpResponse('You are not alowed here!!')
    
    # If user quiere borrar sala 
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
           
    return render(request, 'base/delete.html', {
        'obj':room
    })



# View para borrar mensajes
@login_required(login_url='base:login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk) # Busca sala por id

    # Maneja si algun user quiere eliminar un post de otro usuario
    if request.user != message.user:
        return HttpResponse('You are not alowed here!!')
    
    # If user quiere borrar sala 
    if request.method == 'POST':
        message.delete()
        return redirect('base:home')
           
    return render(request, 'base/delete.html', {'obj':message})


@login_required(login_url='base:login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('base:user-profile', pk=user.id)

    context = {'form':form}
    return render(request, 'base/update-user.html', context)


# Manejo de topics para el mobile menu
def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else '' # Obtiene q del browser 

    topics = Topic.objects.filter(name__icontains=q)

    context = {'topics':topics}
    return render(request, 'base/topics.html', context)


def activityPage(request):
    room_messages = Message.objects.all()

    context = {'room_messages':room_messages,}
    return render(request, 'base/activity.html', context)

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>

    {% for message in room_messages %}
        <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'base:user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{ message.user }}
                    <span>{{ message.created|timesince }} ago</span>
                </p>
                </a>

                {% if request.user == message.user %}
                <div class="roomListRoom__actions">
                    <a href="{% url 'base:delete-message' message.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>Remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                        ></path>
                        </svg>
                    </a>
                </div>
                {% endif %}

            </div>
            <div class="activities__boxContent">
                <p>Replied to post “<a href="{% url 'base:room' message.room.id %}">{{ message.room }}</a>”</p>
                <div class="activities__boxRoomContent">
                    {{ message.body }}
                </div>
            </div>
        </div>
    {% endfor %}

  </div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    
    <p>Are you sure you want to delete "{{obj}}"?</p>

    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

base/templates/base/delete_old.html
{% extends 'main.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    
    <p>Are you sure you want to delete "{{obj}}"?</p>

    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'base:home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'base:topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'base:activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Room</h2>
          <p>{{ room_count }} Rooms available</p>
        </div>

        <a class="btn btn--main" href="{% url 'base:create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
      </div>

      {% include 'base/feed_component.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}
    <!-- Activities End -->

  </div>
</main>

{% endblock content %}  

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}

    <main class="auth layout">

      {% if page == 'login' %}
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" action="" method="POST">
              {% csrf_token %}
              <div class="form__group form__group">
                <label for="room_name">Username or email adress</label>
                <input id="username" name="email" type="text" placeholder="e.g. ezequiel_molina" />
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
            </form>

            <div class="auth__action">
              <p>Haven't signed up yet?</p>
              <a href="{% url 'base:register' %}" class="btn btn--link">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
      {% else %}
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Register</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" action="" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <div class="form__group form__group">
                <label for="room_name">{{field.label}}</label>
                {{field}}
              </div>
              {% endfor %}



              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Register
              </button>
            </form>

            <div class="auth__action">
              <p>Already signed up?</p>
              <a href="{% url 'base:login' %}" class="btn btn--link">Login</a>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </main>
{% endblock content %}

base/templates/base/login_register_old.html
{% extends 'main.html' %}

{% block content %}

{% if page == 'login' %}

<div>
    <form method="POST" action="">
        {% csrf_token %}

        <label>Email:</label>
        <input type="text" name="email" placeholder="Enter Email">

        <label>Password:</label>
        <input type="Password" name="password" placeholder="Enter Password">

        <input type="submit" value="Login">
    </form>

    <p>Haven't signed up yet?</p>
    <a href="{% url 'base:register' %}">Sign up</a>
</div>

{% else %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">
    </form>

    <p>Already signed up?</p>
    <a href="{% url 'base:login' %}">Login</a>
</div>

{% endif %}

{% endblock content %}

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'base/topics_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{user.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{ user.username }}</h3>
            <p>@{{ user.username }}</p>
            {% if request.user == user %}
            <a href="{% url 'base:update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {% if user.bio %}
                {{user.bio}}
              {% else %}
                No description.
              {% endif %}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{user.username}}</a>
            </h2>
          </div>
        </div>
        {% include 'base/feed_component.html' %}

      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'base/activity_component.html' %}
      <!-- Activities End -->
    </div>
  </main>
{% endblock content %}

base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<h1>{{ user.username }}</h1>

<div class="profile-container">
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/feed_component.html' %}
    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>
</div>

{% endblock content %}

base/templates/base/room.html
{% extends 'main.html' %}

{% block content %}

    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'base:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>

            {% if room.host == request.user %}
            <div class="room__topRight">
              <a href="{% url 'base:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'base:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
          </div>

          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{room.name}}</h3>
                <span>{{room.created|timesince}} ago</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'base:user-profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.avatar.url}}" />
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>

<!--               <div class="room__details">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tenetur laudantium? Dicta repellendus
                rerum consectetur, voluptatem repudiandae eum ea porro cupiditate provident nulla, deserunt, ab ipsum
                corporis laboriosam deleniti molestias?
              </div> -->

              <span class="room__topics">{{ room.topic }} </span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">

                {% for message in room_messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'base:user-profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{message.user.avatar.url}}" />
                        </div>
                        <span>@{{ message.user.username }}</span>
                      </a>
                      <span class="thread__date">{{message.created|timesince}} ago</span>
                    </div>

                    {% if message.user == request.user %}
                    <a href="{% url 'base:delete-message' message.id %}">
                      <div class="thread__delete">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </div>
                    </a>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                    {{message.body}}
                  </div>
                </div>
                {% endfor %}

              </div>
            </div>
          </div>
          <div class="room__message">
            <form action="" method="POST">
              {% csrf_token %}
              <input name="body" placeholder="Write your message here..." />
            </form>
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>{{ participants.count }}</span></h3>
          <div class="participants__list scroll">
            {% for user in participants %}
            <a href="{% url 'base:user-profile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{user.avatar.url}}" />
              </div>
              <p>
                {{ user.username }}
                <span>@{{ user.username }}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    <script src="script.js"></script>
{% endblock content %}

base/templates/base/room_form_old.html
{% extends 'main.html' %}

{% block content %}

    <div>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="submit" />
        </form>
    </div>

{% endblock content %}

base/templates/base/topics_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'base:home' %}" class="active">All <span>{{ topics.count }}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{%  url 'base:home' %}?q={{topic.name}}">{{ topic.name }}<span>{{topic.room_set.all.count}}</span></a>
      </li>
      {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'base:topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>